#rewards collection config
api:
  version: v1
application:
  name   : RewardsCollectionAPI
  version: 1.0.0
  domain : 'localhost:8080'
  homeDir: '.'
logging:
  level : DEBUG
  format: >-
    %{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} ->
    %{level:.4s} %{id:03x}%{color:reset} %{message}
middleware:
  enable:
    - Recovery
    - Logging
    - RateLimit
    - CORS
    - AUTH
  ratelimit:
    interval : 1s
    capacity : 10000
    cacheSize: 1000
  cors:
    origin:
      allowed:
      # - http://127.0.0.1
#user token
user:
  token:
    timeout:
      0.5h

#backend database
database:
  default: mysql
  postgres:
    connection: 'postgres://postgres:baas1234_@localhost/baas?sslmode=disable'
  mysql:
    connection: 'heco_mainnet_usrc:v9uB_gTm0zQmBQST@tcp(master-3413.huobiidc.com:3413)/heco_mainnet?charset=utf8&parseTime=True&loc=Local'


#rewards collection connect server by docker server
server:
  archiveNodeUrl: "http://172.26.21.201:8545"
  archiveNode1Url: "http://172.26.22.65:8545"
  archiveNode2Url: "http://172.26.22.26:8545"

#log for mainnet info
log:
  kafka:
    servers:
      - kafka-01.sinnet.huobiidc.com:9092,
      - kafka-02.sinnet.huobiidc.com:9092,
      - kafka-03.sinnet.huobiidc.com:9092,
      - kafka-04.sinnet.huobiidc.com:9092,
      - kafka-05.sinnet.huobiidc.com:9092,
      - kafka-06.sinnet.huobiidc.com:9092
#      - kafka-1c-5.aws-jp1.huobiidc.com:9092,
#      - kafka-1c-3.aws-jp1.huobiidc.com:9092,
#      - kafka-1a-2.aws-jp1.huobiidc.com:9092
  level: 5
  topic: "applog-heco"

#signer gateway
gateway:
  sysAddr: "0x4188d0da3a993f77bbbb57e15c16dccf035c1ef8"
  accessKey: "gateway.defi"
  secretKey: "k4bugMLxrotg2eAY"
  url: "https://192.168.28.13:9000/gateway/sign"


#validator
validator:
  accessKey: "validatorUHEH9B"
  secretKey: "bbaed91482fa1299b6a888e30"
  url: "http://blockchain-validator-1-1c-1.aws-jp1.huobiidc.com:4014/validate/cross/check"

#common config
common:
  epDuration: 36
  votingContractProxyAddr: "0x80d1769ac6fee59BE5AAC1952a90270bbd2Ceb2F"